### ISSUE TITLE
need restfull APIs~

### ISSUE THREAD

**Issue by Magnibronzeball** [williamfzc/srctx#60]
Hi master，Is there any consideration of opening up the restfull API for other languages to call? For example, if I use JAVA, it would be troublesome for me to access the data of FuncGraph.

**Comment by williamfzc** [comment]
Unfortunately no, srctx is designed as a golang lib / commandline tool rather than a webserver.
There are some workarounds for your scene:

- `srctx diff --outputJson ./output.json` and consume the output json in Java;
- Write a simple go script to extract what you need, and save them to your place; (like https://github.com/williamfzc/srctx/blob/main/example/api_test.go)
- Wrap your own webserver;

**Comment by Magnibronzeball** [comment]
Great advice, thanks a lot!
